# Generated by Django 5.0.1 on 2025-12-21 23:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investments', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Nombre')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto reservado')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('converted', 'Convertida a Inversión'), ('expired', 'Expirada'), ('cancelled', 'Cancelada')], default='pending', max_length=20, verbose_name='Estado')),
                ('access_token', models.CharField(editable=False, max_length=64, unique=True, verbose_name='Token de acceso')),
                ('expires_at', models.DateTimeField(verbose_name='Fecha de expiración')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('converted_investment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_reservation', to='investments.investment', verbose_name='Inversión convertida')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'db_table': 'reservations',
                'ordering': ['-created_at'],
            },
        ),
    ]
