# Generated by Django 5.0.1 on 2025-12-21 23:22

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('short_description', models.CharField(blank=True, max_length=500, verbose_name='Descripción corta')),
                ('location', models.CharField(max_length=255, verbose_name='Ubicación')),
                ('address', models.TextField(blank=True, verbose_name='Dirección')),
                ('target_amount', models.DecimalField(decimal_places=2, help_text='Monto total a recaudar', max_digits=14, verbose_name='Monto objetivo')),
                ('minimum_investment', models.DecimalField(decimal_places=2, default=Decimal('1000000.00'), help_text='Monto mínimo para invertir', max_digits=10, verbose_name='Inversión mínima')),
                ('current_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Monto recaudado')),
                ('annual_return_rate', models.DecimalField(decimal_places=2, help_text='Tasa de retorno anual en porcentaje', max_digits=5, verbose_name='Rentabilidad anual (%)')),
                ('duration_months', models.PositiveIntegerField(default=12, help_text='Duración del proyecto en meses', verbose_name='Duración (meses)')),
                ('funding_start_date', models.DateField(verbose_name='Inicio de financiación')),
                ('funding_end_date', models.DateField(verbose_name='Fin de financiación')),
                ('project_start_date', models.DateField(blank=True, null=True, verbose_name='Inicio del proyecto')),
                ('project_end_date', models.DateField(blank=True, null=True, verbose_name='Fin del proyecto')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('funding', 'En Financiación'), ('funded', 'Financiado'), ('in_progress', 'En Ejecución'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], default='draft', max_length=20, verbose_name='Estado')),
                ('main_image', models.ImageField(upload_to='project_images/%Y/%m/', verbose_name='Imagen principal')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destacado')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'db_table': 'projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('image', models.ImageField(upload_to='project_images/%Y/%m/', verbose_name='Imagen')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Descripción')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Imagen de proyecto',
                'verbose_name_plural': 'Imágenes de proyecto',
                'db_table': 'project_images',
                'ordering': ['order'],
            },
        ),
    ]
