# Generated by Django 5.0.1 on 2025-12-21 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='main_image_url',
            field=models.URLField(blank=True, help_text='URL externa de la imagen (alternativa a subir archivo)', max_length=500, null=True, verbose_name='URL de imagen principal'),
        ),
        migrations.AlterField(
            model_name='project',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='project_images/%Y/%m/', verbose_name='Imagen principal'),
        ),
    ]
