# Generated by Django 5.0.1 on 2025-12-21 23:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Nombre')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('source', models.CharField(choices=[('website', 'Sitio Web'), ('reservation', 'Reserva'), ('webhook', 'Webhook Externo'), ('manual', 'Ingreso Manual'), ('referral', 'Referido')], default='website', max_length=20, verbose_name='Fuente')),
                ('source_detail', models.CharField(blank=True, help_text='Información adicional sobre la fuente', max_length=255, verbose_name='Detalle de fuente')),
                ('status', models.CharField(choices=[('new', 'Nuevo'), ('contacted', 'Contactado'), ('interested', 'Interesado'), ('converted', 'Convertido'), ('not_interested', 'No Interesado'), ('invalid', 'Inválido')], default='new', max_length=20, verbose_name='Estado')),
                ('assigned_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de asignación')),
                ('converted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de conversión')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('webhook_data', models.JSONField(blank=True, null=True, verbose_name='Datos del webhook')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'db_table': 'leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadInteraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('interaction_type', models.CharField(choices=[('call', 'Llamada'), ('email', 'Email'), ('meeting', 'Reunión'), ('whatsapp', 'WhatsApp'), ('note', 'Nota')], max_length=20, verbose_name='Tipo de interacción')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('outcome', models.CharField(blank=True, max_length=255, verbose_name='Resultado')),
            ],
            options={
                'verbose_name': 'Interacción con lead',
                'verbose_name_plural': 'Interacciones con leads',
                'db_table': 'lead_interactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
