# Generated by Django 5.0.1 on 2025-12-21 23:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='assigned_to',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'executive'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL, verbose_name='Ejecutivo asignado'),
        ),
        migrations.AddField(
            model_name='lead',
            name='converted_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_origin', to=settings.AUTH_USER_MODEL, verbose_name='Usuario convertido'),
        ),
        migrations.AddField(
            model_name='lead',
            name='interested_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interested_leads', to='projects.project', verbose_name='Proyecto de interés'),
        ),
        migrations.AddField(
            model_name='leadinteraction',
            name='executive',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_interactions', to=settings.AUTH_USER_MODEL, verbose_name='Ejecutivo'),
        ),
        migrations.AddField(
            model_name='leadinteraction',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='leads.lead', verbose_name='Lead'),
        ),
    ]
