# Generated by Django 5.0.1 on 2025-12-21 23:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KYCSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('full_name', models.CharField(max_length=255, verbose_name='Nombre completo')),
                ('document_number', models.CharField(blank=True, max_length=50, verbose_name='Número de documento')),
                ('document_photo', models.ImageField(upload_to='kyc_documents/%Y/%m/', verbose_name='Foto del documento')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado')], default='pending', max_length=20, verbose_name='Estado')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Razón de rechazo')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de revisión')),
                ('auto_processed', models.BooleanField(default=False, verbose_name='Procesado automáticamente')),
            ],
            options={
                'verbose_name': 'Solicitud KYC',
                'verbose_name_plural': 'Solicitudes KYC',
                'db_table': 'kyc_submissions',
                'ordering': ['-created_at'],
            },
        ),
    ]
