# Generated by Django 5.0.1 on 2025-12-21 23:22

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto invertido')),
                ('status', models.CharField(choices=[('pending_payment', 'Pendiente de Pago'), ('payment_review', 'Pago en Revisión'), ('active', 'Activa'), ('completed', 'Completada'), ('cancelled', 'Cancelada')], default='pending_payment', max_length=20, verbose_name='Estado')),
                ('annual_return_rate_snapshot', models.DecimalField(decimal_places=2, help_text='Tasa de retorno al momento de invertir', max_digits=5, verbose_name='Rentabilidad anual (%)')),
                ('duration_months_snapshot', models.PositiveIntegerField(help_text='Duración en meses al momento de invertir', verbose_name='Duración (meses)')),
                ('activated_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de activación')),
                ('expected_end_date', models.DateField(blank=True, null=True, verbose_name='Fecha esperada de término')),
                ('actual_end_date', models.DateField(blank=True, null=True, verbose_name='Fecha real de término')),
                ('expected_return', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Retorno esperado')),
                ('actual_return', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Retorno real')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
            ],
            options={
                'verbose_name': 'Inversión',
                'verbose_name_plural': 'Inversiones',
                'db_table': 'investments',
                'ordering': ['-created_at'],
            },
        ),
    ]
