# Generated by Django 5.0.1 on 2025-12-21 23:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentProof',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('proof_image', models.ImageField(upload_to='payment_proofs/%Y/%m/', verbose_name='Imagen del comprobante')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('bank_name', models.CharField(blank=True, max_length=100, verbose_name='Banco')),
                ('transaction_reference', models.CharField(blank=True, max_length=100, verbose_name='Número de transacción')),
                ('transaction_date', models.DateField(blank=True, null=True, verbose_name='Fecha de transacción')),
                ('status', models.CharField(choices=[('pending', 'Pendiente de Revisión'), ('approved', 'Aprobado'), ('rejected', 'Rechazado')], default='pending', max_length=20, verbose_name='Estado')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de revisión')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Razón de rechazo')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_proofs', to='investments.investment', verbose_name='Inversión')),
            ],
            options={
                'verbose_name': 'Comprobante de Pago',
                'verbose_name_plural': 'Comprobantes de Pago',
                'db_table': 'payment_proofs',
                'ordering': ['-created_at'],
            },
        ),
    ]
